<?php

namespace App;

class EnvVars
{
    const HUBSPOT_CLIENT_ID = 'HUBSPOT_CLIENT_ID';
    const HUBSPOT_CLIENT_SECRET = 'HUBSPOT_CLIENT_SECRET';
    const HUBSPOT_REDIRECT_URI = 'HUBSPOT_REDIRECT_URI';
    const HUBSPOT_AUTH_URL = 'HUBSPOT_AUTH_URL';
    const HUBSPOT_TOKEN_URL = 'HUBSPOT_TOKEN_URL';
    const HUBSPOT_CONTACTS_URL = 'HUBSPOT_CONTACTS_URL';
    const HUBSPOT_TOKEN_SCOPE = 'HUBSPOT_TOKEN_SCOPE';
    const FRONTEND_URL = 'FRONTEND_URL';
    const SQLITE_DB = 'SQLITE_DB';
    const PAGE_SIZE = 'PAGE_SIZE';
}
